### ISSUE TITLE
Checklist for hardfork of Mirana

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#2]
- [x] Display addresses in new format by default and show deprecated format in address info
- [x] Support sending transaction with `data1`
- [x] Synchronize cells of `data1` script
- [ ] <del>set hash type default to be `data1` instead of `data` in preset scripts</del>: there's only one script of hash type 'data' but it has been deprecated.
